### ISSUE TITLE
[BUG] Unable to use shift ability

### ISSUE THREAD

**Issue by samuelhorobin** [CubesCocktail/CubesCocktail#6]
**Describe the bug**
Unable to use shift ability

**To Reproduce**
Uncertain

**Expected behavior**
Shift ability occurrence 

**Minecraft Server Version:**
1.19.3 Paper

**Installed Addons:**
 - ItemDrink
 - EnchantDrink

**Additional context**

> [20:12:25 ERROR]: Could not pass event PlayerToggleSneakEvent to CubesCocktail v0.1.1
> java.lang.NullPointerException: Cannot invoke "com.github.zamponimarco.enchantdrink.enchant.Enchant.getEnchantmentOptions()" because the return value of "com.github.zamponimarco.enchantdrink.manager.EnchantManager.getById(java.util.UUID)" is null
>         at com.github.zamponimarco.enchantdrink.skill.TriggeredSkill.lambda$onTrigger$1(TriggeredSkill.java:102) ~[?:?]
>         at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204) ~[?:?]
>         at java.util.stream.IntPipeline$10$1.accept(IntPipeline.java:393) ~[?:?]
>         at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
>         at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
>         at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
>         at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateSequential(ForEachOps.java:188) ~[?:?]
>         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
>         at java.util.stream.IntPipeline.forEach(IntPipeline.java:463) ~[?:?]
>         at com.github.zamponimarco.enchantdrink.skill.TriggeredSkill.onTrigger(TriggeredSkill.java:97) ~[?:?]
>         at com.github.zamponimarco.cubescocktail.listener.PlayerItemListener.lambda$onPlayerSneak$13(PlayerItemListener.java:113) ~[cubescocktail-0.1.1.jar:?]
>         at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
>         at com.github.zamponimarco.cubescocktail.listener.PlayerItemListener.onPlayerSneak(PlayerItemListener.java:113) ~[cubescocktail-0.1.1.jar:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor678.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-420]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-420]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-420]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2627) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:37) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:13) ~[?:?]
>         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
>         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-420]
>         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
>         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
>         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-420]
>         at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-420]
>         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
>         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-420]
>         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-420]
>         at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-420]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-420]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-420]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ZamponiMarco** [comment]
I suspect this bug is only related to EnchantDrink actually
